# Generated by Django 6.0.2 on 2026-02-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('quality', 'Quality & Risk'), ('technical', 'Technical & HSE')], max_length=50),
        ),
    ]
